import { IncomingMessage, ServerResponse } from 'http';
import * as crypto from 'crypto';
import * as url from 'url';
import axios from 'axios';

const COOKIE_NAME = 'shield_dos_clearance';
const SECRET = process.env.COOKIE_SECRET || 'shield_dos_super_secret_key_123';

export const handleChallenge = async (req: IncomingMessage, res: ServerResponse, site: any): Promise<boolean> => {
    // Returns true if the request was handled (blocked/challenged/verified), false if it should pass through

    const clientIp = typeof req.headers['x-forwarded-for'] === 'string'
        ? req.headers['x-forwarded-for'].split(',')[0].trim()
        : req.socket.remoteAddress || 'unknown';

    // 1. Check for valid clearance cookie
    const cookieHeader = req.headers.cookie || '';
    const cookies = cookieHeader.split(';').reduce((acc, cookie) => {
        const [name, value] = cookie.trim().split('=');
        if (name && value) acc[name] = value;
        return acc;
    }, {} as Record<string, string>);

    if (cookies[COOKIE_NAME]) {
        try {
            // Using '|' delimiter to support IPv4 IPs which naturally contain dots.
            const parts = cookies[COOKIE_NAME].split('|');
            console.log(`[WAF Debug] Checking Cookie: ${cookies[COOKIE_NAME]} - Parts:`, parts);
            if (parts.length === 3) {
                const [hash, ipStr, timestamp] = parts;

                // Verify HMAC signature
                const expectedHash = crypto.createHmac('sha256', SECRET).update(`${ipStr}|${timestamp}`).digest('hex');
                console.log(`[WAF Debug] Expected Hash: ${expectedHash}, Actual: ${hash}, ClientIP: ${clientIp}, CookieIP: ${ipStr}`);

                if (hash === expectedHash && ipStr === clientIp) {
                    // Verify expiration (30 minutes)
                    if (Date.now() - parseInt(timestamp) < 1 * 60 * 1000) {
                        console.log(`[WAF Debug] Clearance VALID! Passing through.`);
                        return false; // Valid clearance, pass through to proxy
                    } else {
                        console.log(`[WAF Debug] Clearance EXPIRED! (Time delta: ${Date.now() - parseInt(timestamp)})`);
                    }
                } else {
                    console.log(`[WAF Debug] Hash MISMATCH or IP mismatch!`);
                }
            } else {
                console.log(`[WAF Debug] Cookie format invalid (parts length != 3).`);
            }
        } catch (e) {
            console.error(`[WAF Debug] Decryption error:`, e);
            // Invalid cookie format, continue to challenge
        }
    }

    // 2. Turnstile Verification POST request has been removed. 
    // PoW is used exclusively.

    // 2.5 Handle PoW Verification POST request
    if (req.method === 'POST' && req.url?.startsWith('/__shield_pow_verify')) {
        return new Promise((resolve) => {
            const parsedUrl = url.parse(req.url || '/', true);
            const originalUrl = (parsedUrl.query.original_url as string) || '/';

            let body = '';
            req.on('data', chunk => {
                body += chunk.toString();
                if (body.length > 1e4) req.socket.destroy();
            });

            req.on('end', () => {
                const searchParams = new URLSearchParams(body);
                const nonce = searchParams.get('nonce') || '';
                const powChallenge = searchParams.get('powChallenge') || '';
                const powTimestamp = parseInt(searchParams.get('powTimestamp') || '0', 10);

                // Verify timestamp (max 5 minutes)
                if (Date.now() - powTimestamp > 5 * 60 * 1000) {
                    serveChallengePage(res, site, originalUrl, clientIp);
                    resolve(true);
                    return;
                }

                // Verify signature of the challenge to ensure it was generated by us for this IP
                const expectedChallenge = crypto.createHmac('sha256', SECRET).update(`${clientIp}|${powTimestamp}`).digest('hex');
                if (powChallenge !== expectedChallenge) {
                    serveChallengePage(res, site, originalUrl, clientIp);
                    resolve(true);
                    return;
                }

                // Verify PoW Hash
                const hash = crypto.createHash('sha256').update(powChallenge + nonce).digest('hex');
                if (hash.startsWith('0000')) {
                    // Success! Issue Clearance Cookie
                    const timestamp = Date.now();
                    const cookieHash = crypto.createHmac('sha256', SECRET).update(`${clientIp}|${timestamp}`).digest('hex');
                    const clearanceCookie = `${cookieHash}|${clientIp}|${timestamp}`;

                    res.writeHead(302, {
                        'Set-Cookie': `${COOKIE_NAME}=${clearanceCookie}; Path=/; HttpOnly; Max-Age=60; SameSite=Lax`,
                        'Location': originalUrl
                    });
                    res.end();
                } else {
                    serveChallengePage(res, site, originalUrl, clientIp);
                }
                resolve(true);
            });
        });
    }

    // 3. Serve the HTML Challenge Page
    serveChallengePage(res, site, req.url || '/', clientIp);
    return true; // Handled
};

function serveChallengePage(res: ServerResponse, site: any, originalUrl: string, clientIp: string) {
    // ShieldDOS Native Cryptographic PoW (Hashcash)
    const powTimestamp = Date.now();
    const powChallenge = crypto.createHmac('sha256', SECRET).update(`${clientIp}|${powTimestamp}`).digest('hex');

    const fallbackHtml = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <title>Verifying your browser...</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
            body { display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100vh; margin: 0; background: #ffffff; color: #333; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; }
            .card { text-align: center; max-width: 400px; padding: 40px; }
            .loader { border: 3px solid #f3f3f3; border-top: 3px solid #f58220; border-radius: 50%; width: 40px; height: 40px; animation: spin 1s linear infinite; margin: 0 auto 20px auto; }
            h1 { font-size: 24px; font-weight: 500; margin-bottom: 10px; color: #111; }
            p { color: #555; font-size: 15px; margin-bottom: 20px; line-height: 1.5; }
            .footer { margin-top: 30px; font-size: 12px; color: #999; }
            @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }
        </style>
        <script>
            (async function() {
                const challenge = "${powChallenge}";
                const timestamp = "${powTimestamp}";
                let nonce = 0;
                const difficulty = "0000";

                async function solve() {
                    if (!window.crypto || !window.crypto.subtle) {
                        // Fallback if HTTP or unsupported browser
                        setTimeout(submitForm, 3000);
                        return;
                    }

                    const encoder = new TextEncoder();
                    while(true) {
                        const data = encoder.encode(challenge + nonce);
                        const hashBuffer = await crypto.subtle.digest('SHA-256', data);
                        const hashArray = Array.from(new Uint8Array(hashBuffer));
                        const hashHex = hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
                        
                        if (hashHex.startsWith(difficulty)) {
                            submitForm(nonce);
                            return;
                        }
                        nonce++;
                        if (nonce % 2000 === 0) {
                            // Yield to main thread
                            await new Promise(r => setTimeout(r, 0));
                        }
                    }
                }

                function submitForm(solvedNonce = 0) {
                    const form = document.createElement('form');
                    form.method = 'POST';
                    form.action = '/__shield_pow_verify?original_url=' + encodeURIComponent('${originalUrl}');
                    
                    const inputNonce = document.createElement('input');
                    inputNonce.type = 'hidden';
                    inputNonce.name = 'nonce';
                    inputNonce.value = solvedNonce;
                    form.appendChild(inputNonce);

                    const inputChall = document.createElement('input');
                    inputChall.type = 'hidden';
                    inputChall.name = 'powChallenge';
                    inputChall.value = challenge;
                    form.appendChild(inputChall);

                    const inputTs = document.createElement('input');
                    inputTs.type = 'hidden';
                    inputTs.name = 'powTimestamp';
                    inputTs.value = timestamp;
                    form.appendChild(inputTs);

                    document.body.appendChild(form);
                    form.submit();
                }

                // Start solving
                solve();
            })();
        </script>
    </head>
    <body>
        <div class="card">
            <div class="loader"></div>
            <h1>Checking your browser...</h1>
            <p>Please wait while we verify your browser. This process is automatic and prevents automated bot attacks.</p>
            <div class="footer">
                <div>Secured by ShieldDOS WAF</div>
                <div style="font-family: monospace; margin-top: 5px;">Ray ID: ${crypto.randomBytes(8).toString('hex')}</div>
            </div>
        </div>
    </body>
    </html>
    `;
    res.writeHead(200, { 'Content-Type': 'text/html', 'Cache-Control': 'no-cache, no-store, must-revalidate' });
    res.write(fallbackHtml);
    res.end();
}
